### ISSUE TITLE
"Land_Pod_Heli_Transport_04_bench_F﻿﻿﻿﻿﻿" no attached butron in the roll menu

### ISSUE THREAD

**Issue by odinsvobik** [BdMdesigN/Igiload-Reloaded#4]
Unable to attached "Land_Pod_Heli_Transport_04_bench_F", the "menu button" does not appear

**Comment by BdMdesigN** [comment]
Fixed. I had test all Pods, the black  Pods was buggy, too. Is fixed now, too.
